### ISSUE TITLE
convert output of pointsToPoly

### ISSUE THREAD

**Issue by emhart** [ropensci-archive/mdextract#17]
This currently returns a matrix.  We probably want it to return something more user friendly to EML such as the gpolygon. Care to chime in on this @cboettig ?  My understanding is it it's just an ordered vector of pairs where each odd point is a latitude, and each even point is a longitude.  Is this true for WKT polygon's @sckott ?

**Comment by sckott** [comment]
You can more or less lint WKT polygons. There are functions in `rgeos` I think that will do converstions for you from and to WKT. e.g., `rgeos::readWKT` and `rgeos::writeWKT`

a polygon looks like `POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))` and a multipolygon looks like `POLYGON ((35 10, 45 45, 15 40, 10 20, 35 10),
(20 30, 35 35, 30 20, 20 30))` - there are many other types though, e.g, point, linestring, etc

**Comment by emhart** [comment]
Looks like I won't need to do this after a close reading of the EML gpoly standard.
